import { useEffect, useMemo, useState } from "react";
import { Boxes, IndianRupee, Package, Search, ShoppingBag, Star, TrendingDown, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ImageWithFallback from "./ImageWithFallback";
import { formatMoney } from "./UI";

export default function AdminCeoProductsOverview({ payload, onControlProduct }) {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(null);
  const products = payload?.products || [];
  const stats = payload?.stats || {};
  const filtered = useMemo(() => products.filter((product) => {
    const term = search.trim().toLowerCase();
    const matches = !term || [product.productName, product.sku, product.category, product.description].some((value) => String(value || "").toLowerCase().includes(term));
    return matches && (status === "all" || product.status === status);
  }), [products, search, status]);
  const pageSize = 10;
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const safePage = Math.min(page, totalPages);
  const visible = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);
  useEffect(() => setPage(1), [search, status]);
  const stockChart = products.slice().sort((a, b) => Number(b.stock || 0) - Number(a.stock || 0)).slice(0, 8).map((row) => ({ name: row.productName, stock: Number(row.stock || 0), revenue: Number(row.revenue || 0) }));
  const totalRevenue = products.reduce((sum, row) => sum + Number(row.revenue || 0), 0);

  return <div className="space-y-6">
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Package} label="Total Products" value={stats.totalProducts || 0} color="#4F46E5" /><Metric icon={ShoppingBag} label="Active Products" value={stats.activeProducts || 0} color="#10B981" /><Metric icon={Boxes} label="Total Stock" value={Number(stats.totalStock || 0).toLocaleString("en-IN")} color="#F59E0B" /><Metric icon={IndianRupee} label="Product Revenue" value={formatMoney(totalRevenue)} color="#8B5CF6" /></div>

    <div className="grid gap-6 xl:grid-cols-2"><SellerSection title="Top Selling Products" subtitle="Highest sales volume" icon={TrendingUp} rows={payload?.topSellingProducts || []} tone="top" onView={setSelected} /><SellerSection title="Low Selling Products" subtitle="Products needing attention" icon={TrendingDown} rows={payload?.lowSellingProducts || []} tone="low" onView={setSelected} /></div>

    <section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-lg shadow-slate-200/50"><div><h2 className="font-black text-slate-950">Stock & Revenue Overview</h2><p className="mt-1 text-xs text-slate-500">Stock position for the eight highest-stock products</p></div>{stockChart.length ? <div className="mt-5 h-72"><ResponsiveContainer><BarChart data={stockChart} margin={{ bottom: 45 }}><defs><linearGradient id="productStock" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4F46E5" /><stop offset="100%" stopColor="#8B5CF6" /></linearGradient></defs><CartesianGrid stroke="#E5E7EB" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" angle={-20} textAnchor="end" interval={0} tick={{ fill: "#64748B", fontSize: 10 }} /><YAxis allowDecimals={false} tick={{ fill: "#64748B", fontSize: 11 }} /><Tooltip content={<StockTooltip />} /><Bar dataKey="stock" fill="url(#productStock)" radius={[8, 8, 0, 0]} animationDuration={900} /></BarChart></ResponsiveContainer></div> : <Empty text="No stock data available." />}</section>

    <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/50 md:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-lg font-black text-slate-950">Product Stock & Revenue</h2><p className="mt-1 text-sm text-slate-500">Detailed product catalog without horizontal scrolling.</p></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative min-w-72"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search product, SKU, category…" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-100" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-700 outline-none focus:ring-4 focus:ring-indigo-100"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div><div className="my-5 h-px bg-slate-100" />
      {visible.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">{visible.map((product) => <ProductCard key={product.id} product={product} onView={() => setSelected(product)} onControl={() => onControlProduct(product)} />)}</div> : <Empty text="No products match the selected filters." />}
      <Pagination page={safePage} totalPages={totalPages} totalItems={filtered.length} pageSize={pageSize} onPage={setPage} />
    </section>
    {selected && <ProductModal product={selected} onClose={() => setSelected(null)} onControl={async () => { await onControlProduct(selected); setSelected(null); }} />}
  </div>;
}

function SellerSection({ title, subtitle, icon: Icon, rows, tone, onView }) { return <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/50"><header className="mb-4 flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone === "top" ? "bg-emerald-50 text-emerald-600" : "bg-orange-50 text-orange-600"}`}><Icon size={20} /></span><div><h2 className="font-black text-slate-950">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div></header>{rows.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{rows.map((product, index) => <button key={product.id} onClick={() => onView(product)} className="group overflow-hidden rounded-xl border border-slate-100 bg-slate-50 text-left transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:bg-white hover:shadow-lg"><div className="relative h-28 bg-slate-100"><ProductImage product={product} /><span className={`absolute left-2 top-2 rounded-lg px-2 py-1 text-[10px] font-black text-white ${tone === "top" ? "bg-emerald-600" : "bg-orange-500"}`}>#{index + 1}</span></div><div className="p-3"><p className="truncate text-sm font-black text-slate-900">{product.productName}</p><p className="mt-1 truncate font-mono text-[10px] font-bold text-indigo-600">SKU: {product.sku || "Not assigned"}</p><div className="mt-3 flex justify-between text-[11px]"><span className="text-slate-500">Sold <strong className="text-slate-800">{product.soldQuantity || 0}</strong></span><span className="font-black text-emerald-600">{formatMoney(product.revenue || 0)}</span></div></div></button>)}</div> : <Empty text="No sales data available." compact />}</section>; }
function ProductCard({ product, onView, onControl }) { const active = product.status === "active"; return <article className="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><div className="relative h-40 bg-slate-100"><ProductImage product={product} /><span className={`absolute right-3 top-3 rounded-full border px-2.5 py-1 text-[10px] font-black capitalize ${active ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-slate-200 bg-white text-slate-600"}`}>{product.status || "inactive"}</span></div><div className="p-4"><p className="truncate font-black text-slate-950">{product.productName}</p><p className="mt-1 truncate font-mono text-xs font-bold text-indigo-600">SKU: {product.sku || "Not assigned"}</p><p className="mt-1 truncate text-xs text-slate-400">{product.category || "Uncategorized"}</p><div className="mt-4 grid grid-cols-3 rounded-xl bg-slate-50 p-3 text-center"><Small label="Stock" value={product.stock || 0} /><Small label="Sold" value={product.soldQuantity || 0} /><Small label="Revenue" value={formatMoney(product.revenue || 0)} /></div><div className="mt-4 flex gap-2"><button onClick={onView} className="flex-1 rounded-xl bg-indigo-50 py-2 text-xs font-black text-indigo-700 hover:bg-indigo-100">Details</button><button onClick={onControl} className={`flex-1 rounded-xl py-2 text-xs font-black text-white ${active ? "bg-rose-600 hover:bg-rose-700" : "bg-emerald-600 hover:bg-emerald-700"}`}>{active ? "Deactivate" : "Activate"}</button></div></div></article>; }
function ProductModal({ product, onClose, onControl }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="grid md:grid-cols-[230px_1fr]"><div className="h-56 bg-slate-100 md:h-full"><ProductImage product={product} /></div><div className="p-6"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-indigo-600">{product.category || "Product"}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{product.productName}</h2><p className="mt-2 font-mono text-sm font-bold text-slate-500">SKU: {product.sku || "Not assigned"}</p></div><button onClick={onClose} className="h-10 rounded-xl bg-slate-100 px-3 text-sm font-black text-slate-600">Close</button></div><p className="mt-4 text-sm leading-6 text-slate-600">{product.description || "No product description has been provided."}</p><div className="mt-5 grid grid-cols-2 gap-3"><Info label="Current stock" value={product.stock || 0} /><Info label="Units sold" value={product.soldQuantity || 0} /><Info label="Revenue" value={formatMoney(product.revenue || 0)} /><Info label="Credit coins" value={product.creditCoins || 0} /></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black text-slate-700">Close</button><button onClick={onControl} className={`rounded-xl px-4 py-2.5 text-sm font-black text-white ${product.status === "active" ? "bg-rose-600" : "bg-emerald-600"}`}>{product.status === "active" ? "Deactivate product" : "Activate product"}</button></div></div></div></div></div>; }
function ProductImage({ product }) { return product.image ? <ImageWithFallback src={product.image} alt={product.productName} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" fallbackClassName="h-full w-full" /> : <div className="grid h-full w-full place-items-center bg-gradient-to-br from-indigo-50 to-purple-100 text-indigo-300"><Package size={44} strokeWidth={1.3} /></div>; }
function Metric({ icon: Icon, label, value, color }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/50 transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl" style={{ color, backgroundColor: `${color}14` }}><Icon size={23} /></span></div></div>; }
function Small({ label, value }) { return <div className="min-w-0 px-1"><p className="truncate text-[9px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 truncate text-[11px] font-black text-slate-800">{value}</p></div>; }
function Info({ label, value }) { return <div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-black text-slate-900">{value}</p></div>; }
function Empty({ text, compact }) { return <div className={`grid place-items-center rounded-xl border border-dashed border-slate-200 bg-slate-50 text-center text-sm font-semibold text-slate-400 ${compact ? "min-h-32" : "min-h-48"}`}><div><Package className="mx-auto mb-2" size={34} strokeWidth={1.3} /><p>{text}</p></div></div>; }
function Pagination({ page, totalPages, totalItems, pageSize, onPage }) { if (!totalItems) return null; const start = (page - 1) * pageSize + 1, end = Math.min(page * pageSize, totalItems); return <div className="mt-6 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-bold text-slate-400">Showing {start}–{end} of {totalItems} products</p><div className="flex gap-2"><button disabled={page === 1} onClick={() => onPage(page - 1)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black disabled:opacity-40">Previous</button><span className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-black text-white">{page} / {totalPages}</span><button disabled={page === totalPages} onClick={() => onPage(page + 1)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black disabled:opacity-40">Next</button></div></div>; }
function StockTooltip({ active, payload, label }) { const row = payload?.[0]?.payload; return active && row ? <div className="rounded-xl border border-slate-200 bg-white p-3 text-sm shadow-xl"><p className="font-black text-slate-900">{label}</p><p className="mt-1">Stock: <strong>{row.stock}</strong></p><p className="text-emerald-600">Revenue: <strong>{formatMoney(row.revenue)}</strong></p></div> : null; }
