import { useMemo, useState } from "react";
import { AlertCircle, Banknote, Box, CalendarDays, CheckCircle2, Clock3, CreditCard, IndianRupee, MapPin, PackageCheck, Search, Store, Truck, WalletCards, XCircle } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatDate, formatMoney } from "./UI";
import { formatTitleCase } from "../utils/textFormatter";

const orderColors = { pending: "#F59E0B", approved: "#3B82F6", packing: "#8B5CF6", shipping: "#06B6D4", out_for_delivery: "#F97316", delivered: "#10B981", rejected: "#EF4444", cancelled: "#EF4444" };
const deliverySteps = ["approved", "packing", "shipping", "out_for_delivery", "delivered"];
const tone = (status) => ({ pending: "border-amber-200 bg-amber-50 text-amber-700", approved: "border-blue-200 bg-blue-50 text-blue-700", packing: "border-purple-200 bg-purple-50 text-purple-700", shipping: "border-cyan-200 bg-cyan-50 text-cyan-700", out_for_delivery: "border-orange-200 bg-orange-50 text-orange-700", delivered: "border-emerald-200 bg-emerald-50 text-emerald-700", rejected: "border-rose-200 bg-rose-50 text-rose-700", cancelled: "border-rose-200 bg-rose-50 text-rose-700" }[status] || "border-slate-200 bg-slate-50 text-slate-600");

export function AdminCeoOrdersOverview({ payload }) {
  const rows = payload?.recentOrders || [];
  const [filter, setFilter] = useState("all"), [search, setSearch] = useState(""), [page, setPage] = useState(1), [selected, setSelected] = useState(null);
  const statuses = payload?.statusCounts || {};
  const filtered = useMemo(() => rows.filter((order) => (filter === "all" || order.status === filter) && (!search || [order.orderNumber, order.Dealer?.dealerName, order.Dealer?.city].some((value) => String(value || "").toLowerCase().includes(search.toLowerCase())))), [rows, filter, search]);
  const visible = filtered.slice((page - 1) * 10, page * 10), totalPages = Math.max(1, Math.ceil(filtered.length / 10));
  const chart = Object.entries(statuses).map(([name, value]) => ({ name: name.replaceAll("_", " "), status: name, value }));
  const amount = rows.reduce((sum, row) => sum + Number(row.totalAmount || 0), 0);
  return <div className="space-y-6"><MetricGrid items={[[Box, "Total Orders", rows.length, "#4F46E5"], [Clock3, "Pending", statuses.pending || 0, "#F59E0B"], [PackageCheck, "Delivered", statuses.delivered || 0, "#10B981"], [IndianRupee, "Order Value", formatMoney(amount), "#8B5CF6"]]} />
    <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><Panel title="Order Distribution" subtitle="Orders grouped by current status"><div className="relative h-72">{chart.length ? <><ResponsiveContainer><PieChart><Pie data={chart} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={3} animationDuration={900}>{chart.map((row) => <Cell key={row.status} fill={orderColors[row.status] || "#64748B"} />)}</Pie><Tooltip content={<ChartTip />} /><Legend /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="mb-8 text-center"><p className="text-3xl font-black">{rows.length}</p><p className="text-xs font-bold text-slate-400">ORDERS</p></div></div></> : <Empty text="No orders available" />}</div></Panel>
      <Panel title="Order Workflow" subtitle="Volume across fulfillment stages"><div className="h-72"><ResponsiveContainer><BarChart data={chart}><CartesianGrid stroke="#E5E7EB" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 10, fill: "#64748B" }} /><YAxis allowDecimals={false} /><Tooltip content={<ChartTip />} /><Bar dataKey="value" radius={[8, 8, 0, 0]} animationDuration={900}>{chart.map((row) => <Cell key={row.status} fill={orderColors[row.status] || "#64748B"} />)}</Bar></BarChart></ResponsiveContainer></div></Panel></div>
    <Panel title="Order Management" subtitle="Review order, dealer, product and fulfillment details"><Toolbar search={search} setSearch={(value) => { setSearch(value); setPage(1); }} filter={filter} setFilter={(value) => { setFilter(value); setPage(1); }} options={Object.keys(statuses)} placeholder="Search order number or dealer…" />{visible.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((order) => <OrderCard key={order.id} order={order} onView={() => setSelected(order)} />)}</div> : <Empty text="No orders match these filters" />}<Pager page={Math.min(page, totalPages)} total={totalPages} count={filtered.length} setPage={setPage} /></Panel>
    {selected && <OrderModal order={selected} onClose={() => setSelected(null)} />}
  </div>;
}

export function AdminCeoDeliveryOverview({ payload }) {
  const rows = payload?.deliveries || [], stats = payload?.stats || {};
  const [filter, setFilter] = useState("all"), [selected, setSelected] = useState(null);
  const filtered = filter === "all" ? rows : rows.filter((row) => row.status === filter);
  const statusRows = deliverySteps.map((status) => ({ status, label: status.replaceAll("_", " "), count: rows.filter((row) => row.status === status).length }));
  return <div className="space-y-6"><MetricGrid items={[[Truck, "Active Deliveries", stats.activeDeliveries || 0, "#4F46E5"], [CheckCircle2, "Delivered", stats.deliveredDeliveries || 0, "#10B981"], [AlertCircle, "Delayed", stats.delayedDeliveries || 0, "#EF4444"], [CalendarDays, "Due This Week", stats.dueThisWeek || 0, "#F59E0B"]]} />
    <Panel title="Delivery Pipeline" subtitle="Live movement through each fulfillment stage"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{statusRows.map((row, index) => <button key={row.status} onClick={() => setFilter(filter === row.status ? "all" : row.status)} className={`relative overflow-hidden rounded-2xl border p-4 text-left transition duration-300 hover:-translate-y-1 hover:shadow-lg ${filter === row.status ? tone(row.status) : "border-slate-100 bg-slate-50"}`}><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white shadow-sm"><Truck size={18} style={{ color: orderColors[row.status] }} /></span><strong className="text-2xl text-slate-950">{row.count}</strong></div><p className="mt-4 text-xs font-black uppercase tracking-wide text-slate-600">{row.label}</p><div className="mt-3 h-1.5 rounded-full bg-white"><div className="h-full rounded-full" style={{ width: `${rows.length ? Math.max(8, row.count / rows.length * 100) : 0}%`, background: orderColors[row.status] }} /></div>{index < 4 && <span className="absolute right-[-9px] top-1/2 hidden h-4 w-4 rotate-45 border-r border-t border-slate-200 bg-slate-50 xl:block" />}</button>)}</div></Panel>
    <Panel title="Delivery Monitoring" subtitle={`${filtered.length} deliveries shown • select a status above to filter`}><div className="mt-2 flex flex-wrap gap-2">{["all", ...deliverySteps].map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-full px-4 py-2 text-xs font-black capitalize transition ${filter === status ? "bg-indigo-600 text-white shadow-md" : "bg-slate-100 text-slate-600 hover:bg-indigo-50"}`}>{status.replaceAll("_", " ")}</button>)}</div>{filtered.length ? <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((order) => <DeliveryCard key={order.id} order={order} onView={() => setSelected(order)} />)}</div> : <Empty text="No deliveries in this stage" />}</Panel>
    {selected && <OrderModal order={selected} onClose={() => setSelected(null)} delivery />}
  </div>;
}

export function AdminCeoFinanceOverview({ payload }) {
  const payments = payload?.payments || [], stats = payload?.stats || {};
  const grouped = useMemo(() => Object.values(payments.reduce((acc, payment) => { const id = payment.dealerId || payment.Dealer?.id || "unknown"; acc[id] ||= { id, dealer: payment.Dealer, total: 0, paid: 0, pending: 0, payments: 0, lastPayment: null }; const row = acc[id]; row.total += Number(payment.amount || 0); row.payments += 1; if (payment.paymentStatus === "paid") row.paid += Number(payment.amount || 0); else row.pending += Number(payment.amount || 0); const date = payment.paidAt || payment.createdAt; if (!row.lastPayment || new Date(date) > new Date(row.lastPayment)) row.lastPayment = date; return acc; }, {})).sort((a, b) => b.total - a.total), [payments]);
  const [search, setSearch] = useState(""), [filter, setFilter] = useState("all"), [page, setPage] = useState(1);
  const filtered = grouped.filter((row) => (!search || [row.dealer?.dealerName, row.dealer?.city, row.dealer?.area].some((value) => String(value || "").toLowerCase().includes(search.toLowerCase()))) && (filter === "all" || (filter === "paid" ? row.pending === 0 : row.pending > 0)));
  const visible = filtered.slice((page - 1) * 10, page * 10), totalPages = Math.max(1, Math.ceil(filtered.length / 10));
  const ratio = [{ name: "Paid", value: Number(stats.paidAmount || 0), color: "#10B981" }, { name: "Outstanding", value: Number(stats.unpaidAmount || 0), color: "#EF4444" }];
  const trend = Object.values(payments.reduce((acc, row) => { const key = new Date(row.paidAt || row.createdAt).toISOString().slice(0, 7); acc[key] ||= { key, month: new Date(`${key}-01`).toLocaleString("en", { month: "short" }), paid: 0, pending: 0 }; acc[key][row.paymentStatus === "paid" ? "paid" : "pending"] += Number(row.amount || 0); return acc; }, {})).sort((a, b) => a.key.localeCompare(b.key)).slice(-6);
  return <div className="space-y-6"><MetricGrid items={[[IndianRupee, "Total Revenue", formatMoney(stats.totalRevenue || 0), "#4F46E5"], [CheckCircle2, "Paid Amount", formatMoney(stats.paidAmount || 0), "#10B981"], [Clock3, "Outstanding", formatMoney(stats.unpaidAmount || 0), "#EF4444"], [CreditCard, "Pending Invoices", stats.pendingInvoices || 0, "#F59E0B"]]} />
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Panel title="Payment Trend" subtitle="Paid and outstanding value over the last six months"><div className="h-72">{trend.length ? <ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="financePaid" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#10B981" stopOpacity=".5" /><stop offset="100%" stopColor="#10B981" stopOpacity=".02" /></linearGradient><linearGradient id="financePending" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#EF4444" stopOpacity=".4" /><stop offset="100%" stopColor="#EF4444" stopOpacity=".02" /></linearGradient></defs><CartesianGrid stroke="#E5E7EB" strokeDasharray="4 4" /><XAxis dataKey="month" /><YAxis tickFormatter={compact} /><Tooltip content={<MoneyTip />} /><Legend /><Area type="monotone" dataKey="paid" stroke="#10B981" strokeWidth={3} fill="url(#financePaid)" /><Area type="monotone" dataKey="pending" stroke="#EF4444" strokeWidth={3} fill="url(#financePending)" /></AreaChart></ResponsiveContainer> : <Empty text="No payment history available" />}</div></Panel>
      <Panel title="Collection Ratio" subtitle="Paid versus outstanding"><div className="relative h-72"><ResponsiveContainer><PieChart><Pie data={ratio} dataKey="value" innerRadius={62} outerRadius={92} paddingAngle={4}>{ratio.map((row) => <Cell key={row.name} fill={row.color} />)}</Pie><Tooltip content={<MoneyTip />} /><Legend /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="mb-8 text-center"><p className="text-2xl font-black">{ratio[0].value + ratio[1].value ? Math.round(ratio[0].value / (ratio[0].value + ratio[1].value) * 100) : 0}%</p><p className="text-xs font-bold text-slate-400">COLLECTED</p></div></div></div></Panel></div>
    <Panel title="Dealer-wise Payments" subtitle="Consolidated payment position for each dealer—not individual transaction rows"><Toolbar search={search} setSearch={(value) => { setSearch(value); setPage(1); }} filter={filter} setFilter={(value) => { setFilter(value); setPage(1); }} options={["paid", "outstanding"]} placeholder="Search dealer or location…" />{visible.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((row) => <FinanceDealerCard key={row.id} row={row} />)}</div> : <Empty text="No dealer payments match these filters" />}<Pager page={Math.min(page, totalPages)} total={totalPages} count={filtered.length} setPage={setPage} /></Panel>
  </div>;
}

function MetricGrid({ items }) { return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{items.map(([Icon, label, value, color]) => <div key={label} className="group rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/50 transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-500">{typeof label === 'string' ? formatTitleCase(label) : label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl transition group-hover:scale-110" style={{ color, background: `${color}14` }}><Icon size={23} /></span></div><div className="mt-4 h-1.5 rounded-full bg-slate-100"><div className="h-full w-2/3 rounded-full" style={{ background: color }} /></div></div>)}</div>; }
function Panel({ title, subtitle, children }) { return <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/50 md:p-6"><h2 className="font-black text-slate-950">{typeof title === 'string' ? formatTitleCase(title) : title}</h2><p className="mt-1 text-xs text-slate-500">{typeof subtitle === 'string' ? formatTitleCase(subtitle) : subtitle}</p><div className="mt-4">{children}</div></section>; }
function Toolbar({ search, setSearch, filter, setFilter, options, placeholder }) { return <div className="flex flex-col gap-3 sm:flex-row sm:justify-end"><label className="relative min-w-72"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100" /></label><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black capitalize outline-none"><option value="all">All statuses</option>{options.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></div>; }
function OrderCard({ order, onView }) { const items = order.items || []; return <article className="rounded-2xl border border-slate-200 p-5 transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs font-black text-indigo-600">{order.orderNumber || `ORDER-${order.id}`}</p><h3 className="mt-1 font-black text-slate-950">{order.Dealer?.dealerName || "Dealer"}</h3><p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><MapPin size={12} />{[order.Dealer?.area, order.Dealer?.city].filter(Boolean).join(", ") || "Location unavailable"}</p></div><Status status={order.status} /></div><div className="mt-4 rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{items.length} product line{items.length === 1 ? "" : "s"}</p><p className="mt-1 line-clamp-2 text-sm font-semibold text-slate-700">{items.map((item) => `${item.Product?.productName || "Product"} × ${item.quantity}`).join(", ") || "Product details unavailable"}</p></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-slate-400">Order value</p><p className="font-black text-slate-950">{formatMoney(order.totalAmount)}</p></div><button onClick={onView} className="rounded-xl bg-indigo-50 px-4 py-2 text-xs font-black text-indigo-700 hover:bg-indigo-100">View details</button></div></article>; }
function DeliveryCard({ order, onView }) { const current = Math.max(0, deliverySteps.indexOf(order.status)); return <article className="rounded-2xl border border-slate-200 p-5 transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><div className="flex justify-between"><div><p className="font-mono text-xs font-black text-indigo-600">{order.orderNumber}</p><h3 className="mt-1 font-black">{order.Dealer?.dealerName || "Dealer"}</h3></div><Status status={order.status} /></div><div className="mt-5 flex items-center">{deliverySteps.map((step, index) => <div key={step} className="flex flex-1 items-center last:flex-none"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-[10px] font-black ${index <= current ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-400"}`}>{index < current ? "✓" : index + 1}</span>{index < 4 && <span className={`h-1 flex-1 ${index < current ? "bg-indigo-500" : "bg-slate-100"}`} />}</div>)}</div><div className="mt-2 flex justify-between text-[9px] font-bold text-slate-400"><span>Approved</span><span>Delivered</span></div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-slate-400">Expected delivery</p><p className="text-sm font-black">{formatDate(order.deliveryDate)}</p></div><button onClick={onView} className="rounded-xl bg-indigo-50 px-4 py-2 text-xs font-black text-indigo-700">Monitor</button></div></article>; }
function FinanceDealerCard({ row }) { const ratio = row.total ? Math.round(row.paid / row.total * 100) : 0; return <article className="rounded-2xl border border-slate-200 p-5 transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Store size={20} /></span><div><h3 className="font-black text-slate-950">{row.dealer?.dealerName || "Dealer"}</h3><p className="text-xs text-slate-400">{[row.dealer?.area, row.dealer?.city].filter(Boolean).join(", ") || "Location unavailable"}</p></div></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${row.pending ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{row.pending ? "Outstanding" : "Paid"}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Total billed" value={formatMoney(row.total)} /><Mini label="Paid" value={formatMoney(row.paid)} positive /><Mini label="Outstanding" value={formatMoney(row.pending)} danger /><Mini label="Payment records" value={row.payments} /></div><div className="mt-4"><div className="flex justify-between text-xs font-bold"><span className="text-slate-400">Collection progress</span><span className="text-indigo-600">{ratio}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-500" style={{ width: `${ratio}%` }} /></div></div><p className="mt-3 text-xs text-slate-400">Latest activity: {formatDate(row.lastPayment)}</p></article>; }
function OrderModal({ order, onClose, delivery }) { const items = order.items || []; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-6 text-white"><div className="flex justify-between"><div><p className="text-xs font-bold text-indigo-100">{delivery ? "DELIVERY MONITOR" : "ORDER DETAILS"}</p><h2 className="mt-1 text-xl font-black">{order.orderNumber || `Order #${order.id}`}</h2><p className="mt-1 text-sm text-indigo-100">{order.Dealer?.dealerName}</p></div><button onClick={onClose} className="h-10 rounded-xl bg-white/10 px-4 text-sm font-black">Close</button></div></div><div className="p-6"><div className="grid gap-3 sm:grid-cols-4"><Mini label="Status" value={String(order.status).replaceAll("_", " ")} /><Mini label="Order value" value={formatMoney(order.totalAmount)} /><Mini label="Order date" value={formatDate(order.createdAt)} /><Mini label="Delivery date" value={formatDate(order.deliveryDate)} /></div><h3 className="mt-6 font-black">Products</h3><div className="mt-3 space-y-3">{items.map((item, index) => <div key={item.id || index} className="flex justify-between rounded-xl border border-slate-100 bg-slate-50 p-4"><div><p className="font-black">{item.Product?.productName || "Product"}</p><p className="font-mono text-xs text-indigo-600">SKU: {item.Product?.sku || "-"}</p><p className="text-xs text-slate-400">{[item.variantName, item.colorName].filter(Boolean).join(" / ")}</p></div><div className="text-right"><p className="font-black">× {item.quantity}</p><p className="text-sm text-slate-500">{formatMoney(item.price || item.unitPrice || 0)}</p></div></div>)}{!items.length && <Empty text="Product details unavailable" />}</div><div className="mt-6 rounded-2xl bg-indigo-50 p-4"><p className="text-xs font-bold uppercase text-indigo-400">Dealer location</p><p className="mt-1 font-bold text-indigo-950">{[order.Dealer?.address, order.Dealer?.area, order.Dealer?.city, order.Dealer?.pincode].filter(Boolean).join(", ") || "Not provided"}</p></div></div></div></div>; }
function Status({ status }) { return <span className={`h-fit rounded-full border px-2.5 py-1 text-[10px] font-black capitalize ${tone(status)}`}>{String(status || "unknown").replaceAll("_", " ")}</span>; }
function Mini({ label, value, positive, danger }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">{typeof label === 'string' ? formatTitleCase(label) : label}</p><p className={`mt-1 text-sm font-black capitalize ${positive ? "text-emerald-600" : danger ? "text-rose-600" : "text-slate-900"}`}>{value ?? "-"}</p></div>; }
function Pager({ page, total, count, setPage }) { if (!count) return null; return <div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><p className="text-sm font-bold text-slate-400">{count} records</p><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-xl border px-4 py-2 text-sm font-black disabled:opacity-40">Previous</button><span className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-black text-white">{page} / {total}</span><button disabled={page >= total} onClick={() => setPage(page + 1)} className="rounded-xl border px-4 py-2 text-sm font-black disabled:opacity-40">Next</button></div></div>; }
function Empty({ text }) { return <div className="mt-5 grid min-h-40 place-items-center rounded-xl border border-dashed border-slate-200 bg-slate-50 text-sm font-bold text-slate-400"><div className="text-center"><Box className="mx-auto mb-2" size={36} strokeWidth={1.3} />{text}</div></div>; }
function ChartTip({ active, payload, label }) { return active && payload?.length ? <div className="rounded-xl border bg-white p-3 text-sm shadow-xl"><p className="font-black capitalize">{label || payload[0]?.payload?.name}</p><p className="text-indigo-600">Orders: <strong>{payload[0].value}</strong></p></div> : null; }
function MoneyTip({ active, payload, label }) { return active && payload?.length ? <div className="rounded-xl border bg-white p-3 text-sm shadow-xl"><p className="font-black">{label || payload[0]?.payload?.name}</p>{payload.map((row) => <p key={row.name} style={{ color: row.color }}>{row.name}: <strong>{formatMoney(row.value)}</strong></p>)}</div> : null; }
function compact(value) { return Number(value) >= 100000 ? `₹${(value / 100000).toFixed(1)}L` : Number(value) >= 1000 ? `₹${(value / 1000).toFixed(0)}K` : value; }
